
baseURL      = "https://example.com"
disableKinds = ["page", "section", "taxonomy", "term"]

[outputs]
    home = ["HTML"]

[module]
    [module.hugoVersion]
        min = "0.92.0"

    [[module.imports]]
        path = "github.com/bep/hugo-mod-bootstrap-scss"
